// Importerar typsnitt och global CSS
import { Geist, Geist_Mono } from "next/font/google";
import './globals.css';

// Definierar typsnitt
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata för sidan (titel och beskrivning)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout som sätter upp grundstrukturen i HTML
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Lägger in Bootstrap CSS*/}
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
